/**
 * IBattleCommand.js
 * 
 * Base interface for all battle actions.
 * Follows the Command Pattern to decouple action selection from action execution.
 */
export default class IBattleCommand {
  /**
   * @param {string} type - e.g. 'attack', 'run', 'item', 'switch'
   * @param {object} source - The Pokemon executing the command
   * @param {object} target - The target Pokemon
   * @param {number} priority - Execution priority (higher goes first)
   */
  constructor(type, source, target, priority = 0) {
    this.type = type;
    this.source = source;
    this.target = target;
    this.priority = priority;
  }

  /**
   * Calculate speed for turn ordering.
   * By default, it's the Pokemon's current resolved speed.
   */
  getSpeed() {
    return this.source ? this.source.speed : 0;
  }

  /**
   * Execute the command. 
   * Must be overridden by subclasses.
   * @param {BattleEngine} engine - Reference to the engine state
   * @returns {Array} List of events generated by this command
   */
  execute(engine) {
    throw new Error('IBattleCommand.execute() must be implemented');
  }
}
